<script>
    import { onMount } from 'svelte';
    import { initDelimitation } from '$lib/delimitation.js';

    onMount(() => {
        initDelimitation();
    });
</script>

<section id="intro">
    <h1>Redrawing Power: How Delimitation Could Reshape India's Political Map</h1>
    <p>A visual exploration of shifting political representation.</p>
    <p class="scroll-prompt">Scroll to begin &darr;</p>
</section>

<section id="scrolly">
    <div class="scrolly-map">
        <svg id="map-svg"></svg>
        <div class="tooltip" style="opacity:0;"></div>
        <div class="legend"></div>
    </div>

    <div class="scrolly-text">
        <div class="step" data-step="1">
            <h2>Current Map of India</h2>
            <p>India is a diverse nation with highly unequal population distribution. Uttar Pradesh alone has over 230 million people—more than the entire country of Brazil. Meanwhile, the five southern states combined account for roughly 250 million. The geographic distribution of India's 1.4 billion people is heavily skewed towards the Gangetic plains.</p>
        </div>

        <div class="step" data-step="2">
            <h2>The Democratic Freeze</h2>
            <p>Currently, the 543 seats in the Lok Sabha are allocated based on the 1971 census. The 84th Amendment froze this allocation until after 2026. For over 50 years, states have possessed the exact same political power regardless of their population changes—an unprecedented democratic freeze designed to incentivize family planning.</p>
        </div>

        <div class="step" data-step="3">
            <h2>The Population Reality</h2>
            <p>From 1971 to 2021, India's population more than doubled from 548 million to 1.4 billion. But growth was vastly uneven: Kerala's population grew by 65%, while Bihar's skyrocketed by nearly 150%. If representation matched today's census, the map becomes heavily top-heavy.</p>
        </div>

        <div class="step" data-step="4">
            <h2>Post-Delimitation Projection</h2>
            <p>A strict reallocation based on projected 2026 populations would see Uttar Pradesh jumping from 80 to 143 seats (+63), and Bihar from 40 to 79 (+39). Conversely, Tamil Nadu would drop from 39 to 31 (-8) and Kerala from 20 to 12 (-8). The balance of power shifts dramatically.</p>
        </div>

        <div class="step" data-step="5" data-color="FertilityRate">
            <h2>The Role of Fertility</h2>
            <p>Why the shift? The Total Fertility Rate (TFR) in Bihar remains high at 2.98, while Kerala is at 1.7. Southern states dropped below the replacement rate of 2.1 decades ago. They successfully implemented the very population control policies the Union government demanded in 1971.</p>
        </div>

        <div class="step" data-step="6" data-color="GDPPerCapita">
            <h2>Economic Disconnect</h2>
            <p>This creates a tension: states losing political power are the economic engines. The five southern states represent just 20% of the population but contribute over 30% to India's GDP. Per capita income in Tamil Nadu (₹2.7 lakh) is nearly six times higher than in Bihar (₹46,000).</p>
        </div>

        <div class="step" data-step="7" data-color="TaxContribution">
            <h2>Tax Contribution</h2>
            <p>For every ₹100 contributed to central taxes, states like Karnataka receive just ₹15 back, while Uttar Pradesh receives ₹273 and Bihar ₹922. The fiscal redistribution system relies heavily on the surplus generated by the very states slated to lose parliamentary representation.</p>
        </div>

        <div class="step" data-step="8" data-color="Literacy">
            <h2>Development Outcomes</h2>
            <p>Kerala's literacy rate sits at 96%, compared to Bihar's 61%. Infant mortality in Tamil Nadu is 13 per 1000, while UP is 38. The paradox of the 2026 delimitation is that it effectively punishes human development success with political marginalization.</p>
        </div>

        <div class="step" data-step="9" data-chart="true">
            <h2>The Impending Crisis</h2>
            <p>In a 543-seat Lok Sabha, the Hindi heartland's share could jump from 42% to nearly 50%, enough to form a government virtually unassisted. This forces a fundamental question: In a federal union, should democratic representation purely be 'one person, one vote', or must it balance demographic weight with economic contribution?</p>
        </div>
    </div>
</section>

<section id="outro">
    <p>Data is approximate and used for illustrative purposes.</p>
    <a href="/">Back to Indecoded</a>
</section>
